name: pr-validation-wf
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
jobs:
  pr-validation-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Welcome to the Github actions"
      - name: Second Step
        run: echo "This is second step"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: job 2 step 1
        run: echo "Hello job 2"

